### Importing Libraries

In [22]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import sklearn
from sklearn import preprocessing

### Displaying the version of Libraries used

In [23]:
# Python version
print('Python: {}'.format(sys.version))
# pandas
print('pandas: {}'.format(pd.__version__))
# numpy
print('numpy: {}'.format(np.__version__))
# seaborn
print('seaborn: {}'.format(sns.__version__))
# scikit-learn
print('sklearn: {}'.format(sklearn.__version__))


Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
pandas: 1.4.1
numpy: 1.22.2
seaborn: 0.11.2
sklearn: 1.0.2


# 1. Obese Dataset

In [24]:
obese_df = pd.read_csv('Overall_Obese_Dataset.csv', header=0)  

In [25]:
obese_df.shape

(97413, 26)

In [26]:
obese_df.head()

Ethnicity  Age  Gender  LOS  Bleeding_Risk  VTE_Risk  CKD_Status  \
0          1   83       1   44              0         1           0   
1          1   83       1   44              0         1           0   
2          1   83       1   44              0         1           0   
3          1   83       1   44              0         1           0   
4          1   83       1   44              0         1           0   

   Obesity_status  Comorbidity  Treatment_days  ...  Edoxa_30mg  Edoxa_60mg  \
0               0            1              72  ...           0           0   
1               0            1              71  ...           0           0   
2               0            1              71  ...           0           0   
3               0            1              70  ...           0           0   
4               0            1              70  ...           0           0   

   Riva_10mg  Riva_15mg  Riva_20mg  Mortality  Emergency_visits  Stroke  \
0          0          0          0          1                 3       0   
1          0          0          0          1                 3       0   
2          0          0          0          1                 3       0   
3          0          0          0          1                 3       0   
4          0          0          0          1                 3       0   

   Bleeding  Thrombosis  
0         2           0  
1         2           0  
2         2           0  
3         2           0  
4         2           0  

[5 rows x 26 columns]

In [27]:
obese_df.describe()

Ethnicity           Age        Gender           LOS  Bleeding_Risk  \
count  97413.000000  97413.000000  97413.000000  97413.000000   97413.000000   
mean       1.113435     78.808301      0.475152     33.536294       0.717420   
std        0.427355     11.515017      0.499385     33.362584       0.450256   
min        1.000000     19.000000      0.000000      0.000000       0.000000   
25%        1.000000     74.000000      0.000000     11.000000       0.000000   
50%        1.000000     81.000000      0.000000     23.000000       1.000000   
75%        1.000000     87.000000      1.000000     45.000000       1.000000   
max        3.000000    103.000000      1.000000    267.000000       1.000000   

           VTE_Risk    CKD_Status  Obesity_status   Comorbidity  \
count  97413.000000  97413.000000    97413.000000  97413.000000   
mean       0.994898      0.387289        0.281605      0.842105   
std        0.071246      0.487133        0.449784      0.364644   
min        0.000000      0.000000        0.000000      0.000000   
25%        1.000000      0.000000        0.000000      1.000000   
50%        1.000000      0.000000        0.000000      1.000000   
75%        1.000000      1.000000        1.000000      1.000000   
max        1.000000      1.000000        1.000000      1.000000   

       Treatment_days  ...    Edoxa_30mg    Edoxa_60mg     Riva_10mg  \
count    97413.000000  ...  97413.000000  97413.000000  97413.000000   
mean       513.972581  ...      0.002495      0.001263      0.005215   
std        461.992899  ...      0.049883      0.035512      0.072026   
min          0.000000  ...      0.000000      0.000000      0.000000   
25%         99.000000  ...      0.000000      0.000000      0.000000   
50%        375.000000  ...      0.000000      0.000000      0.000000   
75%        856.000000  ...      0.000000      0.000000      0.000000   
max       1637.000000  ...      1.000000      1.000000      1.000000   

          Riva_15mg     Riva_20mg     Mortality  Emergency_visits  \
count  97413.000000  97413.000000  97413.000000      97413.000000   
mean       0.065535      0.071418      0.491290          2.261136   
std        0.247469      0.257522      0.499927          2.706122   
min        0.000000      0.000000      0.000000          0.000000   
25%        0.000000      0.000000      0.000000          1.000000   
50%        0.000000      0.000000      0.000000          1.000000   
75%        0.000000      0.000000      1.000000          3.000000   
max        1.000000      1.000000      1.000000         34.000000   

             Stroke      Bleeding    Thrombosis  
count  97413.000000  97413.000000  97413.000000  
mean       0.177235      1.991675      0.009917  
std        0.381869      0.090863      0.099087  
min        0.000000      1.000000      0.000000  
25%        0.000000      2.000000      0.000000  
50%        0.000000      2.000000      0.000000  
75%        0.000000      2.000000      0.000000  
max        1.000000      2.000000      1.000000  

[8 rows x 26 columns]

In [28]:
obese_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97413 entries, 0 to 97412
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Ethnicity         97413 non-null  int64
 1   Age               97413 non-null  int64
 2   Gender            97413 non-null  int64
 3   LOS               97413 non-null  int64
 4   Bleeding_Risk     97413 non-null  int64
 5   VTE_Risk          97413 non-null  int64
 6   CKD_Status        97413 non-null  int64
 7   Obesity_status    97413 non-null  int64
 8   Comorbidity       97413 non-null  int64
 9   Treatment_days    97413 non-null  int64
 10  Apixa_10mg        97413 non-null  int64
 11  Apixa_2.5mg       97413 non-null  int64
 12  Apixa_5mg         97413 non-null  int64
 13  Dabi_110mg        97413 non-null  int64
 14  Dabi_150mg        97413 non-null  int64
 15  Dabi_75mg         97413 non-null  int64
 16  Edoxa_30mg        97413 non-null  int64
 17  Edoxa_60mg        97413 non-nul

In [29]:
obese_df.columns

Index(['Ethnicity', 'Age', 'Gender', 'LOS', 'Bleeding_Risk', 'VTE_Risk',
       'CKD_Status', 'Obesity_status', 'Comorbidity', 'Treatment_days',
       'Apixa_10mg', 'Apixa_2.5mg', 'Apixa_5mg', 'Dabi_110mg', 'Dabi_150mg',
       'Dabi_75mg', 'Edoxa_30mg', 'Edoxa_60mg', 'Riva_10mg', 'Riva_15mg',
       'Riva_20mg', 'Mortality', 'Emergency_visits', 'Stroke', 'Bleeding',
       'Thrombosis'],
      dtype='object')

In [30]:
obese_df['Mortality'] = obese_df.Mortality.astype('category')
obese_df['Stroke'] = obese_df.Stroke.astype('category')
obese_df['Bleeding'] = obese_df.Bleeding.astype('category')
obese_df['Thrombosis'] = obese_df.Thrombosis.astype('category')

# Predict Stroke among Patients receiving DOACs

## 1. Decision Trees

In [31]:

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from sklearn import metrics
from sklearn.tree import export_graphviz
from sklearn import tree
from pydotplus import graph_from_dot_data
import graphviz

In [32]:
X = obese_df[['Ethnicity', 'Age', 'Gender', 'LOS', 'Bleeding_Risk', 'VTE_Risk',
       'CKD_Status', 'Obesity_status', 'Comorbidity', 'Treatment_days',
       'Apixa_10mg', 'Apixa_2.5mg', 'Apixa_5mg', 'Dabi_110mg', 'Dabi_150mg',
       'Dabi_75mg', 'Edoxa_30mg', 'Edoxa_60mg', 'Riva_10mg', 'Riva_15mg',
       'Riva_20mg', 'Mortality', 'Emergency_visits', 'Bleeding',
       'Thrombosis']]
y = obese_df[['Stroke']]
normalized_X = preprocessing.normalize(X)
#print(normalized_X[0:2])
standardized_X = preprocessing.scale(X)
#print(standardized_X[0:2])

########################################## Using raw Data
# train test split using stratification
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3, random_state=1,stratify=y)
# decision tree construction 
dt = DecisionTreeClassifier(criterion = 'entropy', random_state=1)
result_DT= dt.fit(X_train, y_train)
#pridiction
y_pred = dt.predict(X_test)
#accuracy
data_accuracy = metrics.accuracy_score(y_test, y_pred)
print("Data Accuracy: ",data_accuracy)
########################################## Using Normalised Data
# train test split using stratification
X_train, X_test, y_train, y_test = train_test_split(normalized_X, y,test_size=0.3, random_state=1,stratify=y)
# decision tree construction 
dt = DecisionTreeClassifier(criterion = 'entropy', random_state=1)
result_DT= dt.fit(X_train, y_train)
#pridiction
y_pred = dt.predict(X_test)
#accuracy
data_accuracy = metrics.accuracy_score(y_test, y_pred)
print("Normalised data Accuracy: ",data_accuracy)
########################################## Using Standardised Data
# train test split using stratification
X_train, X_test, y_train, y_test = train_test_split(standardized_X, y,test_size=0.3, random_state=1,stratify=y)
# decision tree construction 
dt = DecisionTreeClassifier(criterion = 'entropy', random_state=1)
result_DT= dt.fit(X_train, y_train)
#pridiction
y_pred = dt.predict(X_test)
#accuracy
data_accuracy = metrics.accuracy_score(y_test, y_pred)
print("Standardised Accuracy: ",data_accuracy)

Data Accuracy:  0.9970229947987955
Normalised data Accuracy:  0.9921981932658089
Standardised Accuracy:  0.9969203394470298


In [33]:
X = obese_df[['Ethnicity', 'Age', 'Gender', 'LOS', 'Bleeding_Risk', 'VTE_Risk',
       'CKD_Status', 'Obesity_status', 'Comorbidity', 'Treatment_days',
       'Apixa_10mg', 'Apixa_2.5mg', 'Apixa_5mg', 'Dabi_110mg', 'Dabi_150mg',
       'Dabi_75mg', 'Edoxa_30mg', 'Edoxa_60mg', 'Riva_10mg', 'Riva_15mg',
       'Riva_20mg', 'Mortality', 'Emergency_visits', 'Bleeding',
       'Thrombosis']]
y = obese_df[['Stroke']]
normalized_X = preprocessing.normalize(X)
#print(normalized_X[0:2])
standardized_X = preprocessing.scale(X)
#print(standardized_X[0:2])

########################################## Using raw Data
# train test split using stratification
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3, random_state=1,stratify=y)
# decision tree construction 
dt = DecisionTreeClassifier(criterion = 'entropy', random_state=1)
result_DT= dt.fit(X_train, y_train)
#pridiction
y_pred = dt.predict(X_test)
#accuracy
data_accuracy = metrics.accuracy_score(y_test, y_pred)
print("Data Accuracy: ",data_accuracy)
###################################### Tree visualization
#features = ['Ethnicity', 'Age', 'Gender', 'LOS', 'Bleeding_Risk', 'VTE_Risk',
#       'CKD_Status', 'Obesity_status', 'Comorbidity', 'Treatment_days',
#       'Apixa_10mg', 'Apixa_2.5mg', 'Apixa_5mg', 'Dabi_110mg', 'Dabi_150mg',
#       'Dabi_75mg', 'Edoxa_30mg', 'Edoxa_60mg', 'Riva_10mg', 'Riva_15mg',
#       'Riva_20mg']
#cn=['0', '1']
# Setting figure size
#fig = plt.figure(figsize=(25,20))

#tree.plot_tree(dt,
#           feature_names = features, 
#           class_names=cn,
#           filled = True);

# You can save your plot if you want
#fig.savefig('MyTree.png')


Data Accuracy:  0.9970229947987955


In [34]:
print("Classification report:\n")
namez =  ["Stroke=0", "Stroke=1"]
print(metrics.classification_report(y_test, y_pred, target_names=namez, digits=2,output_dict=False)) 
#confusion matrix
print('\n \n \n Confusion Matrix')
print(confusion_matrix(y_test, y_pred))

Classification report:

              precision    recall  f1-score   support

    Stroke=0       1.00      1.00      1.00     24044
    Stroke=1       0.99      0.99      0.99      5180

    accuracy                           1.00     29224
   macro avg       0.99      1.00      0.99     29224
weighted avg       1.00      1.00      1.00     29224


 
 
 Confusion Matrix
[[23998    46]
 [   41  5139]]


In [35]:
# let's create a dictionary of features and their importance values

#feat_dict= {}
#for col, val in zip(X_train.columns, result_DT.feature_importances_):#sorted(zip(X_train.columns, result_DT.feature_importances_),key=lambda x:x[1],reverse=True):
#  feat_dict[col]=val
#feat_df = pd.DataFrame({'Feature':feat_dict.keys(),'Importance':feat_dict.values()})
#print(feat_df)
#print("\n\n\n\n\n sorted")
#print(feat_df.sort_values(by=['Importance'],ascending=False))

## Variable importance - Decision Trees -  All Patients

In [36]:
# Variable importance in classifier
print("Variable importacne in the classifier.")
pd.concat((pd.DataFrame(X_train.columns, columns = ['variable']), 
           pd.DataFrame(result_DT.feature_importances_, columns = ['importance'])), 
          axis = 1).sort_values(by='importance', ascending = False)

Variable importacne in the classifier.


variable  importance
3                LOS    0.419554
1                Age    0.192408
9     Treatment_days    0.150594
22  Emergency_visits    0.060076
21         Mortality    0.044420
2             Gender    0.025921
8        Comorbidity    0.024532
4      Bleeding_Risk    0.020225
24        Thrombosis    0.013023
0          Ethnicity    0.010800
7     Obesity_status    0.010040
23          Bleeding    0.007649
11       Apixa_2.5mg    0.005382
6         CKD_Status    0.004671
12         Apixa_5mg    0.003670
19         Riva_15mg    0.002646
20         Riva_20mg    0.002114
16        Edoxa_30mg    0.001186
10        Apixa_10mg    0.000638
15         Dabi_75mg    0.000172
13        Dabi_110mg    0.000160
18         Riva_10mg    0.000119
14        Dabi_150mg    0.000000
17        Edoxa_60mg    0.000000
5           VTE_Risk    0.000000

## 2. Random Forest

Random Forests are an improvement over bagged decision trees.

A problem with decision trees like CART is that they are greedy. They choose which variable to split on using a greedy algorithm that minimizes error. As such, even with Bagging, the decision trees can have a lot of structural similarities and in turn have high correlation in their predictions.

Combining predictions from multiple models in ensembles works better if the predictions from the sub-models are uncorrelated or at best weakly correlated.

Random forest changes the algorithm for the way that the sub-trees are learned so that the resulting predictions from all of the subtrees have less correlation.

In [37]:
from sklearn.ensemble import RandomForestClassifier

X = obese_df[['Ethnicity', 'Age', 'Gender', 'LOS', 'Bleeding_Risk', 'VTE_Risk',
       'CKD_Status', 'Obesity_status', 'Comorbidity', 'Treatment_days',
       'Apixa_10mg', 'Apixa_2.5mg', 'Apixa_5mg', 'Dabi_110mg', 'Dabi_150mg',
       'Dabi_75mg', 'Edoxa_30mg', 'Edoxa_60mg', 'Riva_10mg', 'Riva_15mg',
       'Riva_20mg', 'Mortality', 'Emergency_visits', 'Bleeding',
       'Thrombosis']]
y = obese_df[['Stroke']]
normalized_X = preprocessing.normalize(X)
#print(normalized_X[0:2])
standardized_X = preprocessing.scale(X)
#print(standardized_X[0:2])

# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3, random_state=1,stratify=y)
# Random Forests construction 
rf = RandomForestClassifier(criterion='entropy', 
                             n_estimators=1000,
                             min_samples_split=2,
                             min_samples_leaf=1,
                             max_features='auto',
                             oob_score=True,
                             random_state=1,
                             n_jobs=-1,
                             verbose= 0)

### fit/train model
result_RF = rf.fit(X_train, y_train.values.ravel())

#pridiction
y_pred = rf.predict(X_test)
#accuracy
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
namez =  ["Stroke=0", "Stroke=1"]
print(metrics.classification_report(y_test, y_pred, target_names=namez, digits=2,output_dict=False)) 

#confusion matrix
#species = np.array(y_test).argmax(axis=1)
#predictions = np.array(y_pred).argmax(axis=1)
print("Confusion Matrix")
print(confusion_matrix(y_test, y_pred))



Accuracy: 0.9982548590199836
              precision    recall  f1-score   support

    Stroke=0       1.00      1.00      1.00     24044
    Stroke=1       1.00      0.99      1.00      5180

    accuracy                           1.00     29224
   macro avg       1.00      1.00      1.00     29224
weighted avg       1.00      1.00      1.00     29224

Confusion Matrix
[[24040     4]
 [   47  5133]]


## Variable importance - Random Forest - All Patients

In [38]:
# Variable importance in classifier
print("Variable importacne in the classifier.")
pd.concat((pd.DataFrame(X_train.columns, columns = ['variable']), 
           pd.DataFrame(result_RF.feature_importances_, columns = ['importance'])), 
          axis = 1).sort_values(by='importance', ascending = False)


Variable importacne in the classifier.


variable  importance
3                LOS    0.396547
9     Treatment_days    0.159759
1                Age    0.158871
22  Emergency_visits    0.075543
4      Bleeding_Risk    0.041509
21         Mortality    0.025967
2             Gender    0.024252
8        Comorbidity    0.019249
7     Obesity_status    0.017826
0          Ethnicity    0.014893
6         CKD_Status    0.012350
24        Thrombosis    0.011880
12         Apixa_5mg    0.009307
11       Apixa_2.5mg    0.008686
23          Bleeding    0.005993
20         Riva_20mg    0.004974
19         Riva_15mg    0.004941
10        Apixa_10mg    0.002170
13        Dabi_110mg    0.001550
16        Edoxa_30mg    0.000904
18         Riva_10mg    0.000796
5           VTE_Risk    0.000756
14        Dabi_150mg    0.000478
15         Dabi_75mg    0.000406
17        Edoxa_60mg    0.000393

## 3. K-Nearest Neighbhours 

K-Nearest Neighbors, or KNN for short, is one of the simplest machine learning algorithms and is used in a wide array of institutions. KNN is a non-parametric, lazy learning algorithm. When we say a technique is non-parametric, it means that it does not make any assumptions about the underlying data. In other words, it makes its selection based off of the proximity to other data points regardless of what feature the numerical values represent. Being a lazy learning algorithm implies that there is little to no training phase. Therefore, we can immediately classify new data points as they present themselves.

Pros:
No assumptions about data
Simple algorithm — easy to understand
Can be used for classification and regression
Cons:
High memory requirement — All of the training data must be present in memory in order to calculate the closest K neighbors
Sensitive to irrelevant features
Sensitive to the scale of the data since we’re computing the distance to the closest K points

Source: https://towardsdatascience.com/k-nearest-neighbor-python-2fccc47d2a55


In [39]:
"""
Source: 
https://machinelearningmastery.com/hyperparameters-for-classification-machine-learning-algorithms/
"""
# example of grid searching key hyperparametres for KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier

X = obese_df[['Ethnicity', 'Age', 'Gender', 'LOS', 'Bleeding_Risk', 'VTE_Risk',
       'CKD_Status', 'Obesity_status', 'Comorbidity', 'Treatment_days',
       'Apixa_10mg', 'Apixa_2.5mg', 'Apixa_5mg', 'Dabi_110mg', 'Dabi_150mg',
       'Dabi_75mg', 'Edoxa_30mg', 'Edoxa_60mg', 'Riva_10mg', 'Riva_15mg',
       'Riva_20mg', 'Mortality', 'Emergency_visits', 'Bleeding',
       'Thrombosis']]
y = obese_df[['Stroke']]
normalized_X = preprocessing.normalize(X)
standardized_X = preprocessing.scale(X)

# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3, random_state=1,stratify=y)

# define models and parameters
KNN_model = KNeighborsClassifier()

### fit/train model
result_knn = KNN_model.fit(X_train, y_train.values.ravel())

#pridiction
y_pred = KNN_model.predict(X_test)
#accuracy
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
namez =  ["Stroke=0", "Stroke=1"]
print(metrics.classification_report(y_test, y_pred, target_names=namez, digits=2,output_dict=False)) 

#confusion matrix
print("Confusion Matrix")
print(confusion_matrix(y_test, y_pred))



Accuracy: 0.9918217903093348
              precision    recall  f1-score   support

    Stroke=0       0.99      1.00      1.00     24044
    Stroke=1       0.98      0.98      0.98      5180

    accuracy                           0.99     29224
   macro avg       0.99      0.99      0.99     29224
weighted avg       0.99      0.99      0.99     29224

Confusion Matrix
[[23930   114]
 [  125  5055]]


## 4. Logistic Regression

In [40]:
from sklearn.linear_model import LogisticRegression

X = obese_df[['Ethnicity', 'Age', 'Gender', 'LOS', 'Bleeding_Risk', 'VTE_Risk',
       'CKD_Status', 'Obesity_status', 'Comorbidity', 'Treatment_days',
       'Apixa_10mg', 'Apixa_2.5mg', 'Apixa_5mg', 'Dabi_110mg', 'Dabi_150mg',
       'Dabi_75mg', 'Edoxa_30mg', 'Edoxa_60mg', 'Riva_10mg', 'Riva_15mg',
       'Riva_20mg', 'Mortality', 'Emergency_visits', 'Bleeding',
       'Thrombosis']]
y = obese_df[['Stroke']]

# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3, random_state=1,stratify=y)


# define models and parameters
model_lg = LogisticRegression()

### fit/train model
result_lg = model_lg.fit(X_train, y_train.values.ravel())

#pridiction
y_pred = model_lg.predict(X_test)
#accuracy
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
namez =  ["Stroke=0", "Stroke=1"]
print(metrics.classification_report(y_test, y_pred, target_names=namez, digits=2,output_dict=False)) 

#confusion matrix
print("Confusion Matrix")
print(confusion_matrix(y_test, y_pred))


Accuracy: 0.863947440459896
              precision    recall  f1-score   support

    Stroke=0       0.89      0.96      0.92     24044
    Stroke=1       0.68      0.44      0.53      5180

    accuracy                           0.86     29224
   macro avg       0.78      0.70      0.73     29224
weighted avg       0.85      0.86      0.85     29224

Confusion Matrix
[[22972  1072]
 [ 2904  2276]]


D:\Ayub_Ansari_PhD_Experiments\Dr_Shahzad_Colab\ve_dr_shahzad\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


## 5. Gradient Bossting Classifier

In [41]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import GridSearchCV

X = obese_df[['Ethnicity', 'Age', 'Gender', 'LOS', 'Bleeding_Risk', 'VTE_Risk',
       'CKD_Status', 'Obesity_status', 'Comorbidity', 'Treatment_days',
       'Apixa_10mg', 'Apixa_2.5mg', 'Apixa_5mg', 'Dabi_110mg', 'Dabi_150mg',
       'Dabi_75mg', 'Edoxa_30mg', 'Edoxa_60mg', 'Riva_10mg', 'Riva_15mg',
       'Riva_20mg', 'Mortality', 'Emergency_visits', 'Bleeding',
       'Thrombosis']]
y = obese_df[['Stroke']]
# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3, random_state=1,stratify=y)

# define models and parameters
model_GBC = GradientBoostingClassifier()

### fit/train model
result_GBC = model_GBC.fit(X_train, y_train.values.ravel())

#pridiction
y_pred = model_GBC.predict(X_test)
#accuracy
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
namez =  ["Stroke=0", "Stroke=1"]
print(metrics.classification_report(y_test, y_pred, target_names=namez, digits=2,output_dict=False)) 

#confusion matrix
print("Confusion Matrix")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9095264166438544
              precision    recall  f1-score   support

    Stroke=0       0.91      0.98      0.95     24044
    Stroke=1       0.89      0.56      0.69      5180

    accuracy                           0.91     29224
   macro avg       0.90      0.77      0.82     29224
weighted avg       0.91      0.91      0.90     29224

Confusion Matrix
[[23669   375]
 [ 2269  2911]]


## 6. Support Vector Machine

In [42]:
from sklearn.svm import SVC

X = obese_df[['Ethnicity', 'Age', 'Gender', 'LOS', 'Bleeding_Risk', 'VTE_Risk',
       'CKD_Status', 'Obesity_status', 'Comorbidity', 'Treatment_days',
       'Apixa_10mg', 'Apixa_2.5mg', 'Apixa_5mg', 'Dabi_110mg', 'Dabi_150mg',
       'Dabi_75mg', 'Edoxa_30mg', 'Edoxa_60mg', 'Riva_10mg', 'Riva_15mg',
       'Riva_20mg', 'Mortality', 'Emergency_visits', 'Bleeding',
       'Thrombosis']]
y = obese_df[['Stroke']]
# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3, random_state=1,stratify=y)

# define model and parameters
model_SVM = SVC()

#fit/train model
model_SVM.fit(X_train, y_train.values.ravel())
#### Model prediction
y_predict = model_SVM.predict(X_test)

#accuracy
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
namez =  ["Stroke=0", "Stroke=1"]
print(metrics.classification_report(y_test, y_pred, target_names=namez, digits=2,output_dict=False)) 

#confusion matrix
print("Confusion Matrix")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9095264166438544
              precision    recall  f1-score   support

    Stroke=0       0.91      0.98      0.95     24044
    Stroke=1       0.89      0.56      0.69      5180

    accuracy                           0.91     29224
   macro avg       0.90      0.77      0.82     29224
weighted avg       0.91      0.91      0.90     29224

Confusion Matrix
[[23669   375]
 [ 2269  2911]]
