### Importing Libraries

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import sklearn
from sklearn import preprocessing

### Displaying the version of Libraries used

In [2]:
# Python version
print('Python: {}'.format(sys.version))
# pandas
print('pandas: {}'.format(pd.__version__))
# numpy
print('numpy: {}'.format(np.__version__))
# seaborn
print('seaborn: {}'.format(sns.__version__))
# scikit-learn
print('sklearn: {}'.format(sklearn.__version__))


Python: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
pandas: 1.5.0
numpy: 1.23.3
seaborn: 0.12.0
sklearn: 1.1.2


# 1. CKD Dataset

In [3]:
ckd_df = pd.read_csv('CKD_ML_Final.csv', header=0)  

In [4]:
ckd_df.shape

(97413, 32)

In [5]:
ckd_df.head()

Age  EG_White  EG_BAME  EG_Other  Gender  Comorbidity  Bleeding_Risk  \
0   83         1        0         0       1            1              0   
1   83         1        0         0       1            1              0   
2   83         1        0         0       1            1              0   
3   83         1        0         0       1            1              0   
4   83         1        0         0       1            1              0   

   VTE_Risk    BMI  Treatment_days  ...  Stage3a_CKD  Stage3b_CKD  Stage4_CKD  \
0         1  17.18              72  ...            0            0           0   
1         1  17.18              71  ...            0            0           0   
2         1  17.18              71  ...            0            0           0   
3         1  17.18              70  ...            0            0           0   
4         1  17.18              70  ...            0            0           0   

   Stage5_CKD  Mortality  Bleeding  Stroke  Thrombosis  Emergency_Adm  LoS  
0           0          1         0       0           0              3   44  
1           0          1         0       0           0              3   44  
2           0          1         0       0           0              3   44  
3           0          1         0       0           0              3   44  
4           0          1         0       0           0              3   44  

[5 rows x 32 columns]

In [6]:
ckd_df.describe()

Age      EG_White       EG_BAME      EG_Other        Gender  \
count  97413.000000  97413.000000  97413.000000  97413.000000  97413.000000   
mean      78.808301      0.927597      0.031372      0.041031      0.475152   
std       11.515017      0.259155      0.174321      0.198364      0.499385   
min       19.000000      0.000000      0.000000      0.000000      0.000000   
25%       74.000000      1.000000      0.000000      0.000000      0.000000   
50%       81.000000      1.000000      0.000000      0.000000      0.000000   
75%       87.000000      1.000000      0.000000      0.000000      1.000000   
max      103.000000      1.000000      1.000000      1.000000      1.000000   

        Comorbidity  Bleeding_Risk      VTE_Risk           BMI  \
count  97413.000000   97413.000000  97413.000000  97413.000000   
mean       0.842105       0.717420      0.994898     27.166205   
std        0.364644       0.450256      0.071246      7.172186   
min        0.000000       0.000000      0.000000     15.000000   
25%        1.000000       0.000000      1.000000     22.280000   
50%        1.000000       1.000000      1.000000     25.870000   
75%        1.000000       1.000000      1.000000     30.750000   
max        1.000000       1.000000      1.000000     97.700000   

       Treatment_days  ...   Stage3a_CKD   Stage3b_CKD    Stage4_CKD  \
count    97413.000000  ...  97413.000000  97413.000000  97413.000000   
mean       513.972581  ...      0.188856      0.130106      0.052786   
std        461.992899  ...      0.391396      0.336422      0.223606   
min          0.000000  ...      0.000000      0.000000      0.000000   
25%         99.000000  ...      0.000000      0.000000      0.000000   
50%        375.000000  ...      0.000000      0.000000      0.000000   
75%        856.000000  ...      0.000000      0.000000      0.000000   
max       1637.000000  ...      1.000000      1.000000      1.000000   

         Stage5_CKD     Mortality      Bleeding        Stroke    Thrombosis  \
count  97413.000000  97413.000000  97413.000000  97413.000000  97413.000000   
mean       0.006005      0.491290      0.008325      0.177235      0.009917   
std        0.077262      0.499927      0.090863      0.381869      0.099087   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      1.000000      0.000000      0.000000      0.000000   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

       Emergency_Adm           LoS  
count   97413.000000  97413.000000  
mean        2.261136     33.536294  
std         2.706122     33.362584  
min         0.000000      0.000000  
25%         1.000000     11.000000  
50%         1.000000     23.000000  
75%         3.000000     45.000000  
max        34.000000    267.000000  

[8 rows x 32 columns]

In [7]:
ckd_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97413 entries, 0 to 97412
Data columns (total 32 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Age                    97413 non-null  int64  
 1   EG_White               97413 non-null  int64  
 2   EG_BAME                97413 non-null  int64  
 3   EG_Other               97413 non-null  int64  
 4   Gender                 97413 non-null  int64  
 5   Comorbidity            97413 non-null  int64  
 6   Bleeding_Risk          97413 non-null  int64  
 7   VTE_Risk               97413 non-null  int64  
 8   BMI                    97413 non-null  float64
 9   Treatment_days         97413 non-null  int64  
 10  Apixa_2_5mg            97413 non-null  int64  
 11  Apixa_5mg              97413 non-null  int64  
 12  Apixa_10mg             97413 non-null  int64  
 13  Dabi_75mg              97413 non-null  int64  
 14  Dabi_110mg             97413 non-null  int64  
 15  Da

In [8]:
ckd_df.columns

Index(['Age', 'EG_White', 'EG_BAME', 'EG_Other', 'Gender', 'Comorbidity',
       'Bleeding_Risk', 'VTE_Risk', 'BMI', 'Treatment_days', 'Apixa_2_5mg',
       'Apixa_5mg', 'Apixa_10mg', 'Dabi_75mg', 'Dabi_110mg', 'Dabi_150mg',
       'Edoxa_30mg', 'Edoxa_60', 'Riva_10mg', 'Riva_15mg', 'Riva_20mg',
       'Normal_Renal_Function', 'Stage3a_CKD', 'Stage3b_CKD', 'Stage4_CKD',
       'Stage5_CKD', 'Mortality', 'Bleeding', 'Stroke', 'Thrombosis',
       'Emergency_Adm', 'LoS'],
      dtype='object')

In [9]:
ckd_df['Stroke'] = ckd_df.Stroke.astype('category')

# Predict Stroke among Patients receiving DOACs

## 1. Decision Trees

In [10]:

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from sklearn import metrics
from sklearn.tree import export_graphviz
from sklearn import tree
from pydotplus import graph_from_dot_data
import graphviz

In [12]:
X = ckd_df[['Age', 'EG_White', 'EG_BAME', 'EG_Other', 'Gender', 'Comorbidity',
       'Bleeding_Risk', 'VTE_Risk', 'BMI', 'Treatment_days', 'Apixa_2_5mg',
       'Apixa_5mg', 'Apixa_10mg', 'Dabi_75mg', 'Dabi_110mg', 'Dabi_150mg',
       'Edoxa_30mg', 'Edoxa_60', 'Riva_10mg', 'Riva_15mg', 'Riva_20mg',
       'Normal_Renal_Function', 'Stage3a_CKD', 'Stage3b_CKD', 'Stage4_CKD',
       'Stage5_CKD', 'Mortality', 'Bleeding', 'Thrombosis',
       'Emergency_Adm', 'LoS']]
y = ckd_df[['Stroke']]
normalized_X = preprocessing.normalize(X)
#print(normalized_X[0:2])
standardized_X = preprocessing.scale(X)
#print(standardized_X[0:2])

########################################## Using raw Data
# train test split using stratification
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3, random_state=1,stratify=y)
# decision tree construction 
dt = DecisionTreeClassifier(criterion = 'entropy', random_state=1)
result_DT= dt.fit(X_train, y_train)
#pridiction
y_pred = dt.predict(X_test)
#accuracy
data_accuracy = metrics.accuracy_score(y_test, y_pred)
print("Data Accuracy: ",data_accuracy)
########################################## Using Normalised Data
# train test split using stratification
X_train, X_test, y_train, y_test = train_test_split(normalized_X, y,test_size=0.3, random_state=1,stratify=y)
# decision tree construction 
dt = DecisionTreeClassifier(criterion = 'entropy', random_state=1)
result_DT= dt.fit(X_train, y_train)
#pridiction
y_pred = dt.predict(X_test)
#accuracy
data_accuracy = metrics.accuracy_score(y_test, y_pred)
print("Normalised data Accuracy: ",data_accuracy)
########################################## Using Standardised Data
# train test split using stratification
X_train, X_test, y_train, y_test = train_test_split(standardized_X, y,test_size=0.3, random_state=1,stratify=y)
# decision tree construction 
dt = DecisionTreeClassifier(criterion = 'entropy', random_state=1)
result_DT= dt.fit(X_train, y_train)
#pridiction
y_pred = dt.predict(X_test)
#accuracy
data_accuracy = metrics.accuracy_score(y_test, y_pred)
print("Standardised Accuracy: ",data_accuracy)

Data Accuracy:  0.9978442376129208
Normalised data Accuracy:  0.9952778538187791
Standardised Accuracy:  0.997912674514098


In [13]:
X = ckd_df[['Age', 'EG_White', 'EG_BAME', 'EG_Other', 'Gender', 'Comorbidity',
       'Bleeding_Risk', 'VTE_Risk', 'BMI', 'Treatment_days', 'Apixa_2_5mg',
       'Apixa_5mg', 'Apixa_10mg', 'Dabi_75mg', 'Dabi_110mg', 'Dabi_150mg',
       'Edoxa_30mg', 'Edoxa_60', 'Riva_10mg', 'Riva_15mg', 'Riva_20mg',
       'Normal_Renal_Function', 'Stage3a_CKD', 'Stage3b_CKD', 'Stage4_CKD',
       'Stage5_CKD', 'Mortality', 'Bleeding', 'Thrombosis',
       'Emergency_Adm', 'LoS']]
y = ckd_df[['Stroke']]
normalized_X = preprocessing.normalize(X)
#print(normalized_X[0:2])
standardized_X = preprocessing.scale(X)
#print(standardized_X[0:2])

########################################## Using raw Data
# train test split using stratification
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3, random_state=1,stratify=y)
# decision tree construction 
dt = DecisionTreeClassifier(criterion = 'entropy', random_state=1)
result_DT= dt.fit(X_train, y_train)
#pridiction
y_pred = dt.predict(X_test)
#accuracy
data_accuracy = metrics.accuracy_score(y_test, y_pred)
print("Data Accuracy: ",data_accuracy)
###################################### Tree visualization
#features = ['Ethnicity', 'Age', 'Gender', 'LOS', 'Bleeding_Risk', 'VTE_Risk',
#       'CKD_Status', 'Obesity_status', 'Comorbidity', 'Treatment_days',
#       'Apixa_10mg', 'Apixa_2.5mg', 'Apixa_5mg', 'Dabi_110mg', 'Dabi_150mg',
#       'Dabi_75mg', 'Edoxa_30mg', 'Edoxa_60mg', 'Riva_10mg', 'Riva_15mg',
#       'Riva_20mg']
#cn=['0', '1']
## Setting figure size
#fig = plt.figure(figsize=(25,20))##

#tree.plot_tree(dt,
#           feature_names = features, 
#           class_names=cn,
#           filled = True);

# You can save your plot if you want
#fig.savefig('MyTree.png')


Data Accuracy:  0.9978442376129208


In [14]:
print("Classification report:\n")
namez =  ["Stroke=0", "Stroke=1"]
print(metrics.classification_report(y_test, y_pred, target_names=namez, digits=2,output_dict=False)) 
#confusion matrix
print('\n \n \n Confusion Matrix')
print(confusion_matrix(y_test, y_pred))

Classification report:

              precision    recall  f1-score   support

    Stroke=0       1.00      1.00      1.00     24044
    Stroke=1       0.99      0.99      0.99      5180

    accuracy                           1.00     29224
   macro avg       1.00      1.00      1.00     29224
weighted avg       1.00      1.00      1.00     29224


 
 
 Confusion Matrix
[[24010    34]
 [   29  5151]]


In [15]:
# let's create a dictionary of features and their importance values
#feat_dict= {}
#for col, val in zip(X_train.columns, result_DT.feature_importances_):#sorted(zip(X_train.columns, result_DT.feature_importances_),key=lambda x:x[1],reverse=True):
#  feat_dict[col]=val
#feat_df = pd.DataFrame({'Feature':feat_dict.keys(),'Importance':feat_dict.values()})
#print(feat_df)
#print("\n\n\n\n\n sorted")
#print(feat_df.sort_values(by=['Importance'],ascending=False))

## Variable importance - Decision Trees 

In [16]:
# Variable importance in classifier
print("Variable importacne in the classifier.")
pd.concat((pd.DataFrame(X_train.columns, columns = ['variable']), 
           pd.DataFrame(result_DT.feature_importances_, columns = ['importance'])), 
          axis = 1).sort_values(by='importance', ascending = False)

Variable importacne in the classifier.


variable  importance
30                    LoS    0.391520
0                     Age    0.128591
9          Treatment_days    0.111545
8                     BMI    0.101663
29          Emergency_Adm    0.053776
26              Mortality    0.040387
6           Bleeding_Risk    0.022236
10            Apixa_2_5mg    0.021654
4                  Gender    0.021092
5             Comorbidity    0.020027
11              Apixa_5mg    0.015372
28             Thrombosis    0.014039
3                EG_Other    0.011544
21  Normal_Renal_Function    0.009625
2                 EG_BAME    0.006259
20              Riva_20mg    0.006009
22            Stage3a_CKD    0.005264
24             Stage4_CKD    0.004298
23            Stage3b_CKD    0.003732
18              Riva_10mg    0.003721
1                EG_White    0.002890
27               Bleeding    0.001543
7                VTE_Risk    0.000744
14             Dabi_110mg    0.000725
12             Apixa_10mg    0.000537
17               Edoxa_60    0.000529
25             Stage5_CKD    0.000405
19              Riva_15mg    0.000272
16             Edoxa_30mg    0.000000
13              Dabi_75mg    0.000000
15             Dabi_150mg    0.000000

## 2. Random Forest

Random Forests are an improvement over bagged decision trees.

A problem with decision trees like CART is that they are greedy. They choose which variable to split on using a greedy algorithm that minimizes error. As such, even with Bagging, the decision trees can have a lot of structural similarities and in turn have high correlation in their predictions.

Combining predictions from multiple models in ensembles works better if the predictions from the sub-models are uncorrelated or at best weakly correlated.

Random forest changes the algorithm for the way that the sub-trees are learned so that the resulting predictions from all of the subtrees have less correlation.

In [17]:
from sklearn.ensemble import RandomForestClassifier

X = ckd_df[['Age', 'EG_White', 'EG_BAME', 'EG_Other', 'Gender', 'Comorbidity',
       'Bleeding_Risk', 'VTE_Risk', 'BMI', 'Treatment_days', 'Apixa_2_5mg',
       'Apixa_5mg', 'Apixa_10mg', 'Dabi_75mg', 'Dabi_110mg', 'Dabi_150mg',
       'Edoxa_30mg', 'Edoxa_60', 'Riva_10mg', 'Riva_15mg', 'Riva_20mg',
       'Normal_Renal_Function', 'Stage3a_CKD', 'Stage3b_CKD', 'Stage4_CKD',
       'Stage5_CKD', 'Mortality', 'Bleeding', 'Thrombosis',
       'Emergency_Adm', 'LoS']]
y = ckd_df[['Stroke']]
normalized_X = preprocessing.normalize(X)
#print(normalized_X[0:2])
standardized_X = preprocessing.scale(X)
#print(standardized_X[0:2])

# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3, random_state=1,stratify=y)
# Random Forests construction 
rf = RandomForestClassifier(criterion='entropy', 
                             n_estimators=1000,
                             min_samples_split=2,
                             min_samples_leaf=1,
                             max_features='auto',
                             oob_score=True,
                             random_state=1,
                             n_jobs=-1,
                             verbose= 0)

### fit/train model
result_RF = rf.fit(X_train, y_train.values.ravel())

#pridiction
y_pred = rf.predict(X_test)
#accuracy
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
namez =  ["Stroke=0", "Stroke=1"]
print(metrics.classification_report(y_test, y_pred, target_names=namez, digits=2,output_dict=False)) 

#confusion matrix
#species = np.array(y_test).argmax(axis=1)
#predictions = np.array(y_pred).argmax(axis=1)
print("Confusion Matrix")
print(confusion_matrix(y_test, y_pred))



D:\UoH_PhD_Experiments\Side_effects_of_DOACs_NHS\ve_DOAC_NHS\lib\site-packages\sklearn\ensemble\_forest.py:427: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(


Accuracy: 0.9992129756364632
              precision    recall  f1-score   support

    Stroke=0       1.00      1.00      1.00     24044
    Stroke=1       1.00      1.00      1.00      5180

    accuracy                           1.00     29224
   macro avg       1.00      1.00      1.00     29224
weighted avg       1.00      1.00      1.00     29224

Confusion Matrix
[[24044     0]
 [   23  5157]]


## Variable importance - Random Forest - Morbidly Obese Patients

In [18]:
# Variable importance in classifier
print("Variable importacne in the classifier.")
pd.concat((pd.DataFrame(X_train.columns, columns = ['variable']), 
           pd.DataFrame(result_RF.feature_importances_, columns = ['importance'])), 
          axis = 1).sort_values(by='importance', ascending = False)


Variable importacne in the classifier.


variable  importance
30                    LoS    0.329156
9          Treatment_days    0.125859
0                     Age    0.125751
8                     BMI    0.116662
29          Emergency_Adm    0.068368
6           Bleeding_Risk    0.036588
11              Apixa_5mg    0.030656
26              Mortality    0.023773
4                  Gender    0.022456
5             Comorbidity    0.016826
10            Apixa_2_5mg    0.016822
21  Normal_Renal_Function    0.012767
28             Thrombosis    0.010579
22            Stage3a_CKD    0.008328
23            Stage3b_CKD    0.007403
1                EG_White    0.007355
19              Riva_15mg    0.007246
3                EG_Other    0.006932
20              Riva_20mg    0.006631
27               Bleeding    0.005633
24             Stage4_CKD    0.003990
2                 EG_BAME    0.003637
12             Apixa_10mg    0.001405
7                VTE_Risk    0.001113
14             Dabi_110mg    0.001019
25             Stage5_CKD    0.000910
13              Dabi_75mg    0.000620
18              Riva_10mg    0.000599
16             Edoxa_30mg    0.000404
17               Edoxa_60    0.000391
15             Dabi_150mg    0.000121

## 3. K-Nearest Neighbhours 

K-Nearest Neighbors, or KNN for short, is one of the simplest machine learning algorithms and is used in a wide array of institutions. KNN is a non-parametric, lazy learning algorithm. When we say a technique is non-parametric, it means that it does not make any assumptions about the underlying data. In other words, it makes its selection based off of the proximity to other data points regardless of what feature the numerical values represent. Being a lazy learning algorithm implies that there is little to no training phase. Therefore, we can immediately classify new data points as they present themselves.

Pros:
No assumptions about data
Simple algorithm — easy to understand
Can be used for classification and regression
Cons:
High memory requirement — All of the training data must be present in memory in order to calculate the closest K neighbors
Sensitive to irrelevant features
Sensitive to the scale of the data since we’re computing the distance to the closest K points

Source: https://towardsdatascience.com/k-nearest-neighbor-python-2fccc47d2a55


In [19]:
"""
Source: 
https://machinelearningmastery.com/hyperparameters-for-classification-machine-learning-algorithms/
"""
# example of grid searching key hyperparametres for KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier

X = ckd_df[['Age', 'EG_White', 'EG_BAME', 'EG_Other', 'Gender', 'Comorbidity',
       'Bleeding_Risk', 'VTE_Risk', 'BMI', 'Treatment_days', 'Apixa_2_5mg',
       'Apixa_5mg', 'Apixa_10mg', 'Dabi_75mg', 'Dabi_110mg', 'Dabi_150mg',
       'Edoxa_30mg', 'Edoxa_60', 'Riva_10mg', 'Riva_15mg', 'Riva_20mg',
       'Normal_Renal_Function', 'Stage3a_CKD', 'Stage3b_CKD', 'Stage4_CKD',
       'Stage5_CKD', 'Mortality', 'Bleeding', 'Thrombosis',
       'Emergency_Adm', 'LoS']]
y = ckd_df[['Stroke']]
normalized_X = preprocessing.normalize(X)
standardized_X = preprocessing.scale(X)

# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3, random_state=1,stratify=y)

# define models and parameters
KNN_model = KNeighborsClassifier()

### fit/train model
result_knn = KNN_model.fit(X_train, y_train.values.ravel())

#pridiction
y_pred = KNN_model.predict(X_test)
#accuracy
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
namez =  ["Stroke=0", "Stroke=1"]
print(metrics.classification_report(y_test, y_pred, target_names=namez, digits=2,output_dict=False)) 

#confusion matrix
print("Confusion Matrix")
print(confusion_matrix(y_test, y_pred))



Accuracy: 0.9958937859293732
              precision    recall  f1-score   support

    Stroke=0       1.00      1.00      1.00     24044
    Stroke=1       0.99      0.99      0.99      5180

    accuracy                           1.00     29224
   macro avg       0.99      0.99      0.99     29224
weighted avg       1.00      1.00      1.00     29224

Confusion Matrix
[[23990    54]
 [   66  5114]]


## 4. Logistic Regression

In [20]:
from sklearn.linear_model import LogisticRegression

X = ckd_df[['Age', 'EG_White', 'EG_BAME', 'EG_Other', 'Gender', 'Comorbidity',
       'Bleeding_Risk', 'VTE_Risk', 'BMI', 'Treatment_days', 'Apixa_2_5mg',
       'Apixa_5mg', 'Apixa_10mg', 'Dabi_75mg', 'Dabi_110mg', 'Dabi_150mg',
       'Edoxa_30mg', 'Edoxa_60', 'Riva_10mg', 'Riva_15mg', 'Riva_20mg',
       'Normal_Renal_Function', 'Stage3a_CKD', 'Stage3b_CKD', 'Stage4_CKD',
       'Stage5_CKD', 'Mortality', 'Bleeding', 'Thrombosis',
       'Emergency_Adm', 'LoS']]
y = ckd_df[['Stroke']]

# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3, random_state=1,stratify=y)


# define models and parameters
model_lg = LogisticRegression()

### fit/train model
result_lg = model_lg.fit(X_train, y_train.values.ravel())

#pridiction
y_pred = model_lg.predict(X_test)
#accuracy
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
namez =  ["Stroke=0", "Stroke=1"]
print(metrics.classification_report(y_test, y_pred, target_names=namez, digits=2,output_dict=False)) 

#confusion matrix
print("Confusion Matrix")
print(confusion_matrix(y_test, y_pred))


Accuracy: 0.8644949356693129
              precision    recall  f1-score   support

    Stroke=0       0.89      0.96      0.92     24044
    Stroke=1       0.69      0.43      0.53      5180

    accuracy                           0.86     29224
   macro avg       0.79      0.70      0.73     29224
weighted avg       0.85      0.86      0.85     29224

Confusion Matrix
[[23019  1025]
 [ 2935  2245]]


D:\UoH_PhD_Experiments\Side_effects_of_DOACs_NHS\ve_DOAC_NHS\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


## 5. Gradient Bossting Classifier

In [21]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import GridSearchCV

X = ckd_df[['Age', 'EG_White', 'EG_BAME', 'EG_Other', 'Gender', 'Comorbidity',
       'Bleeding_Risk', 'VTE_Risk', 'BMI', 'Treatment_days', 'Apixa_2_5mg',
       'Apixa_5mg', 'Apixa_10mg', 'Dabi_75mg', 'Dabi_110mg', 'Dabi_150mg',
       'Edoxa_30mg', 'Edoxa_60', 'Riva_10mg', 'Riva_15mg', 'Riva_20mg',
       'Normal_Renal_Function', 'Stage3a_CKD', 'Stage3b_CKD', 'Stage4_CKD',
       'Stage5_CKD', 'Mortality', 'Bleeding', 'Thrombosis',
       'Emergency_Adm', 'LoS']]
y = ckd_df[['Stroke']]
# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3, random_state=1,stratify=y)

# define models and parameters
model_GBC = GradientBoostingClassifier()

### fit/train model
result_GBC = model_GBC.fit(X_train, y_train.values.ravel())

#pridiction
y_pred = model_GBC.predict(X_test)
#accuracy
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
namez =  ["Stroke=0", "Stroke=1"]
print(metrics.classification_report(y_test, y_pred, target_names=namez, digits=2,output_dict=False)) 

#confusion matrix
print("Confusion Matrix")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9114084314262251
              precision    recall  f1-score   support

    Stroke=0       0.92      0.98      0.95     24044
    Stroke=1       0.87      0.59      0.70      5180

    accuracy                           0.91     29224
   macro avg       0.89      0.78      0.82     29224
weighted avg       0.91      0.91      0.90     29224

Confusion Matrix
[[23593   451]
 [ 2138  3042]]


## 6. Support Vector Machine

In [22]:
from sklearn.svm import SVC

XX = ckd_df[['Age', 'EG_White', 'EG_BAME', 'EG_Other', 'Gender', 'Comorbidity',
       'Bleeding_Risk', 'VTE_Risk', 'BMI', 'Treatment_days', 'Apixa_2_5mg',
       'Apixa_5mg', 'Apixa_10mg', 'Dabi_75mg', 'Dabi_110mg', 'Dabi_150mg',
       'Edoxa_30mg', 'Edoxa_60', 'Riva_10mg', 'Riva_15mg', 'Riva_20mg',
       'Normal_Renal_Function', 'Stage3a_CKD', 'Stage3b_CKD', 'Stage4_CKD',
       'Stage5_CKD', 'Mortality', 'Bleeding', 'Thrombosis',
       'Emergency_Adm', 'LoS']]
y = ckd_df[['Stroke']]
# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3, random_state=1,stratify=y)

# define model and parameters
model_SVM = SVC()

#fit/train model
model_SVM.fit(X_train, y_train.values.ravel())
#### Model prediction
y_predict = model_SVM.predict(X_test)

#accuracy
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
namez =  ["Stroke=0", "Stroke=1"]
print(metrics.classification_report(y_test, y_pred, target_names=namez, digits=2,output_dict=False)) 

#confusion matrix
print("Confusion Matrix")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9114084314262251
              precision    recall  f1-score   support

    Stroke=0       0.92      0.98      0.95     24044
    Stroke=1       0.87      0.59      0.70      5180

    accuracy                           0.91     29224
   macro avg       0.89      0.78      0.82     29224
weighted avg       0.91      0.91      0.90     29224

Confusion Matrix
[[23593   451]
 [ 2138  3042]]
